# Generated by Django 3.1.1 on 2020-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dateStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
