# Generated by Django 3.1.1 on 2020-09-06 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200905_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dateStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
